disabled_rules:
# 라인 뒤에 공백이 없어야함
- trailing_whitespace

# XCTFail Message는 설명을 포함
- xctfail_message

# 함수 파라미터가
- function_parameter_count

# 오래된 C 함수보다 새로운 sturct initializer를 사용
- legacy_constructor

# 배열이나 딕셔너리에서 컴마로 끝나지 않도록 함
- trailing_comma

# 식별자 이름 규칙
- identifier_name

# enum케이스와 동일한 값
- redundant_string_enum_value

# 주석처리 스페이싱
- comment_spacing

# 타입/함수/파일 등의 코드길이 제한을 변경하겠다는 뜻
type_body_length: 500
file_length: 500
line_length: 500
function_body_length: 500
